version: '2.1'
services:
  dev-nginx:
    restart: always
    image: nginx:latest
    container_name: dev-nginx
    ports:
      - "8080:80"
    volumes:
      - ../workspace:/home/workspace
      - ./nginx/sites/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/log:/var/log/nginx
    links:
      - dev-php:fpm_php

  dev-php:
    restart: always
    build: ./dockerfiles/php-fpm71
    container_name: dev-php
    volumes:
      - ../workspace:/home/workspace

  dev-mongo:
    restart: always
    image: mongo:3.7
    container_name: dev-mongo
    ports:
      - "27017:27017"
    volumes:
      - ../workspace:/home/workspace